accounts/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^$', views.index, name='index'),

    url(r'^alterar_dados/$', views.update_user, name='update_user'),

    url(r'^alterar_senha/$', views.update_password, name='update_password'),

    url(r'^registro/$', views.register, name='register'),
]

catalog/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),

    url(r'^(?P<slug>[\w_-]+)/$', views.category, name='category'),

    url(r'^produtos/(?P<slug>[\w_-]+)/$', views.product, name='product'),
]

checkout/urls.py
# coding=utf-8

from django.conf.urls import url

from checkout.views import OrderListView
from .views import CreateCartItemView, CartItemView, CheckoutView

urlpatterns = [
    url(
        r'^carrinhol/adicionar/(?P<slug>[\w_-]+)/$',
        CreateCartItemView.as_view(), name='create_cartitem'),

    url(r'^carrinho/$', CartItemView.as_view(), name='cart_item'),

    url(r'^finalizando/$', CheckoutView.as_view(), name='checkout'),

    url(r'^meus_pediso/$', OrderListView.as_view(), name='order_list'),
]

djangoecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from core import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contato/$', views.contact, name='contact'),
    url(r'^entrar/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^sair/$', logout, {'next_page': 'index'}, name='logout'),
    url(r'^catalogo/', include('catalog.urls', namespace='catalog')),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^compras/', include('checkout.urls', namespace='checkout')),
    url(r'^admin/', admin.site.urls),
]

accounts/models.py
# coding=utf-8
import re
from django.core import validators
from django.db import models
from django.contrib.auth.models import (
    AbstractUser, PermissionsMixin, UserManager)


class User(AbstractUser, PermissionsMixin):
    # Modelo de usuario padrao para o sistema

    username = models.CharField(
        'Nome do usuário', max_length=30, unique=True,
        validators=[validators.RegexValidator(re.compile(
            '^[\w.@+-]+$'),
            'O nome de usuário só pode conter os seguintes caracteres:'
            ' @/./+/_', 'invalid')])
    email = models.EmailField('E-mail', unique=True)
    name = models.CharField('Nome completo', max_length=100, blank=True)
    is_active = models.BooleanField('Está ativo?', default=True)
    is_staff = models.BooleanField('É da equipe?', default=False)
    is_superuser = models.BooleanField('É super usuário?', default=False)
    date_joined = models.DateTimeField('Data de criação', auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = "Usuário"
        verbose_name_plural = "Usuários"

    def __str__(self):
        return self.name or self.username

    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        return str(self).split(" ")[0]

    @models.permalink
    def get_absolute_url(self):
        return ('')

accounts/forms.py
# coding=utf-8

from django.contrib.auth.forms import UserCreationForm
from django import forms

from .models import User


class UserAdminCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email']


class UserAdminForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'name', 'is_active', 'is_staff', ]

accounts/views.py
# coding=utf-8

from django.views.generic import CreateView, TemplateView, UpdateView, FormView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import PasswordChangeForm

from .models import User
from .forms import UserAdminCreationForm


class IndexView(LoginRequiredMixin, TemplateView):

    template_name = 'accounts/index.html'


class RegisterView(CreateView):

    model = User
    template_name = 'accounts/register.html'
    form_class = UserAdminCreationForm
    success_url = reverse_lazy('index')


class UpdateUserView(LoginRequiredMixin, UpdateView):

    model = User
    template_name = 'accounts/update_user.html'
    fields = ['name', 'email']
    success_url = reverse_lazy('accounts:index')

    def get_object(self):
        return self.request.user


class UpdatePasswordView(LoginRequiredMixin, FormView):

    template_name = 'accounts/update_password.html'
    success_url = reverse_lazy('accounts:index')
    form_class = PasswordChangeForm

    def get_form_kwargs(self):
        kwargs = super(UpdatePasswordView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        return super(UpdatePasswordView, self).form_valid(form)


index = IndexView.as_view()
register = RegisterView.as_view()
update_user = UpdateUserView.as_view()
update_password = UpdatePasswordView.as_view()

accounts/templates/accounts/index.html
{% extends "base.html" %}

{% block title %}Minha conta{% endblock %}

{% block container %}
    <ol class="breadcrumb">
      <li><a href="{% url 'accounts:index' %}">Início</a></li>
      <li class="active">Minha Conta</li>
    </ol>
    <div class="row">
        <div class="col-md-4">
            <div class="list-group">
                <a href="{% url 'accounts:index' %}" class="list-group-item active">Minha Conta</a>
                <a href="{% url 'accounts:update_user' %}" class="list-group-item">Alterar Dados</a>
                <a href="{% url 'accounts:update_password' %}" class="list-group-item">Alterar Senha</a>
                <a href="{% url 'checkout:order_list' %}" class="list-group-item">Meus Pedidos</a>
            </div>
        </div>
        <div class="col-md-8">
            {% block accounts_container %}
                 <h2>Bem vindo {{ request.user }} </h2>
            {% endblock %}
        </div>
    </div>    
{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block title %}
  Entrar | {{ block.super }}
{% endblock title %}

{% load widget_tweaks %}

{% block container %}
      <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="page-header">
                    <h1>Entrar</h1>
                </div>
                <form class="form-horizontal" method="post">
                    {% csrf_token %}
                    {% for error in form.non_field_errors %}
                      <div class="alert alert-danger">
                        {{ error }}
                      </div>
                    {% endfor %}
                    <fieldset>
                      {% for field in form  %}
                        <div class="form-group {% if field.errors %} has-error {% endif %}">
                          <label for="{{ field.auto_id }}" class="col-md-3 control-label"> {{ field.label }} </label>
                          <div class="col-md-9">
                            {% render_field field class="form-control" %}
                            {% for error in field.erros %}
                              <span class="help-block">{{ error }}</span>
                            {% endfor %}
                          </div>
                        </div>
                      {% endfor %}
                        <div class="form-group">
                          <div class="col-md-9 col-md-offset-3">
                            <button type="submit" class="btn btn-primary">Enviar</button>
                          </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
{% endblock container %}

accounts/templates/accounts/update_password.html
{% extends "accounts/index.html" %}

{% load widget_tweaks %}

{% block title %}Alterar Senha{% endblock %}

{% block accounts_container %}
      <h2>Alterar Senha</h2>
      <form action="" class="form-horizontal" method="post">
          {% csrf_token %}
          <fieldset>
              {% for field in form %}
                <div class="form-group{% if field.errors %} has-error {% endif %}">
                    <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                    <div class="col-md-9">
                        {% render_field field class='form-control' %}
                        {% for error in field.errors %}
                            <span class="help-block">{{ error }}</span>
                        {% endfor %}
                    </div>
                </div>
              {% endfor %}
              <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                      <button type="submit" class="btn btn-primary">Salvar</button>
                  </div>
              </div>
          </fieldset>
      </form>
{% endblock accounts_container %}

accounts/templates/accounts/update_user.html
{% extends "accounts/index.html" %}

{% load widget_tweaks %}

{% block title %}Alterar Dados{% endblock %}

{% block accounts_container %}
      <h2>Alterar Dados</h2>
      <form action="" class="form-horizontal" method="post">
          {% csrf_token %}
          <fieldset>
              {% for field in form %}
                <div class="form-group{% if field.errors %} has-error {% endif %}">
                    <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                    <div class="col-md-9">
                        {% render_field field class='form-control' %}
                        {% for error in field.errors %}
                            <span class="help-block">{{ error }}</span>
                        {% endfor %}
                    </div>
                </div>
              {% endfor %}
              <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                      <button type="submit" class="btn btn-primary">Salvar</button>
                  </div>
              </div>
          </fieldset>
      </form>
{% endblock accounts_container %}