accounts/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^$', views.index, name='index'),

    url(r'^alterar_dados/$', views.update_user, name='update_user'),

    url(r'^alterar_senha/$', views.update_password, name='update_password'),

    url(r'^registro/$', views.register, name='register'),
]

catalog/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),

    url(r'^(?P<slug>[\w_-]+)/$', views.category, name='category'),

    url(r'^produtos/(?P<slug>[\w_-]+)/$', views.product, name='product'),
]

checkout/urls.py
# coding=utf-8

from django.conf.urls import url

from checkout.views import OrderListView
from .views import CreateCartItemView, CartItemView, CheckoutView

urlpatterns = [
    url(
        r'^carrinhol/adicionar/(?P<slug>[\w_-]+)/$',
        CreateCartItemView.as_view(), name='create_cartitem'),

    url(r'^carrinho/$', CartItemView.as_view(), name='cart_item'),

    url(r'^finalizando/$', CheckoutView.as_view(), name='checkout'),

    url(r'^meus_pediso/$', OrderListView.as_view(), name='order_list'),
]

djangoecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from core import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contato/$', views.contact, name='contact'),
    url(r'^entrar/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^sair/$', logout, {'next_page': 'index'}, name='logout'),
    url(r'^catalogo/', include('catalog.urls', namespace='catalog')),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^compras/', include('checkout.urls', namespace='checkout')),
    url(r'^admin/', admin.site.urls),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail


class ContactForm(forms.Form):

    name = forms.CharField(label='None')
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(label='Mensagem', widget=forms.Textarea())

    def send_mail(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        message = self.cleaned_data['message']
        message = 'Nome: {0}\n E-mail:{1}\n{2}'.format(name, email, message)
        send_mail(
            'Mensagem Padrão do Projeto', message, settings.DEFAULT_FROM_EMAIL,
            [settings.DEFAULT_FROM_EMAIL]
        )

core/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render
from django.views.generic import TemplateView

from .forms import ContactForm

User = get_user_model()


class IndexView(TemplateView):
    template_name = 'index.html'

index = IndexView.as_view()


def contact(request):
    success = False
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.send_mail()
        success = True
    context = {
        'form': form,
        'success': success
    }
    return render(request, 'contact.html', context)

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %} Django E-Commerce {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="stylesheet" href= "{% static 'assets/bootstrap.min.css' %}" media="screen" />
    <link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen" />
    <link rel="stylesheet" href="{% static 'assets/extra.css' %}" media="screen" />
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="{% url 'index' %}" class="navbar-brand">Django E-Commerce</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href="{% url 'index' %}">Início</a>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'catalog:product_list' %}" id="download">Categorias <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">

              {% for category in categories  %}
                  <li><a href="{{ category.get_absolute_url }}"> {{ category }} </a></li>
              {% endfor %}

              </ul>
            </li>
            <li>
                <a href="{% url 'contact' %}">Contato</a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Sair</a></li>
          {% else %}
            <li><a href="{% url 'login' %}">Entrar</a></li>
            <li><a href="{% url 'accounts:register' %}">Registro</a></li>
          {% endif %}
            <li><a href="{% url 'checkout:cart_item' %}">Carrinho</a></li>
          </ul>
        </div>
        </div>
        </div>
        <div class="container margin-top">
        {% block messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
              {{ message }}
            </div>
          {% endfor %}
        {% endblock %}
        {% block container %}{% endblock %}
        <footer>
            <div class="row">
              <div class="col-lg-12">
                <ul class="list-unstyled">
                  <li class="pull-right"><a href="#top">Voltar ao Topo</a></li>
                  <li><a href="">Início</a></li>
                  <li><a href="">Produtos</a></li>
                  <li><a href="">Contato</a></li>
                  <li><a href="">Termos e Privacidade</a></li>
                </ul>
              </div>
            </div>
        </footer>
    </div>
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static "assets/bootstrap.min.js" %}"></script>
</body>
</html>

core/templates/contact.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Contato | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>Fale conosco</h1>
    {% if success %}
    <div class="alert alert-success">
        Mensagem enviada com sucesso
    </div>
    {% endif %}
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Enviar</button>
              </div>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}

core/templates/index.html
{% extends "base.html" %}

{% block container %}
<div class="jumbotron page-header">
  <h1>Django E-Commerce</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
  <p><a class="btn btn-primary">Saiba mais</a></p>
</div>
{% endblock %}

core/templates/login.html
{% extends "base.html" %}

{% block title %}
  Entrar | {{ block.super }}
{% endblock title %}    

{% load widget_tweaks %}

{% block container %}
      <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="page-header">
                    <h1>Entrar</h1>
                </div>
                <form class="form-horizontal" method="post">
                    {% csrf_token %}
                    {% for error in form.non_field_errors %}
                      <div class="alert alert-danger">
                        {{ error }}
                      </div>
                    {% endfor %}
                    <fieldset>
                        <div class="form-group {% if form.username.errors %} has-error {% endif %}">
                          <label for="{{ form.username.auto_id }}" class="col-md-3 control-label"> {{ form.username.label }} </label>
                          <div class="col-md-9">
                            {% render_field form.username class="form-control" %}
                            {% for error in form.username.erros %}
                              <span class="help-block">{{ error }}</span>
                            {% endfor %}
                          </div>
                        </div>
                        <div class="form-group {% if form.username.errors %} has-error {% endif %}">
                          <label for="{{ form.password.auto_id }}" class="col-md-3 control-label">{{ form.password.label }}</label>
                          <div class="col-md-9">
                            {% render_field form.password class="form-control" %}
                            {% for error in form.password.erros %}
                              <span class="help-block">{{ error }}</span>
                            {% endfor %}                            
                          </div>
                        </div>
                        <div class="form-group">
                          <div class="col-md-9 col-md-offset-3">
                            <button type="submit" class="btn btn-primary">Enviar</button>
                          </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
{% endblock container %}

core/templates/pagination.html
    <div class="row">
        <div class="col-md-12">
            <nav aria-label="Page navigation">
              <ul class="pagination">
                {% for page in paginator.page_range %}
                    <li {% if page_obj.number == page %} class="active" {% endif %} ><a href="?page={{ page }}">{{ page }}</a></li>
                {% endfor %}
              </ul>
            </nav>
        </div>
    </div> 