catalog/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),

    url(r'^(?P<slug>[\w_-]+)/$', views.category, name='category'),

    url(r'^produtos/(?P<slug>[\w_-]+)/$', views.product, name='product'),
]

checkout/urls.py
# coding=utf-8

from django.conf.urls import url

from checkout.views import OrderListView
from .views import CreateCartItemView, CartItemView, CheckoutView

urlpatterns = [
    url(
        r'^carrinhol/adicionar/(?P<slug>[\w_-]+)/$',
        CreateCartItemView.as_view(), name='create_cartitem'),

    url(r'^carrinho/$', CartItemView.as_view(), name='cart_item'),

    url(r'^finalizando/$', CheckoutView.as_view(), name='checkout'),

    url(r'^meus_pediso/$', OrderListView.as_view(), name='order_list'),
]

djangoecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from core import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contato/$', views.contact, name='contact'),
    url(r'^entrar/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^sair/$', logout, {'next_page': 'index'}, name='logout'),
    url(r'^catalogo/', include('catalog.urls', namespace='catalog')),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^compras/', include('checkout.urls', namespace='checkout')),
    url(r'^admin/', admin.site.urls),
]

catalog/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Category(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Indentificador', max_length=100)

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificao em', auto_now=True)

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:category', kwargs={'slug': self.slug})


class Product(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Indentificador', max_length=100)
    category = models.ForeignKey('catalog.Category', verbose_name='Categoria')
    description = models.TextField('Descrição', blank=True)
    price = models.DecimalField('Preço', max_digits=10, decimal_places=2)

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificao em', auto_now=True)

    class Meta:
        verbose_name = "Produto"
        verbose_name_plural = "Produtos"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product', kwargs={'slug': self.slug})

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic

from .models import Product, Category


class ProductListView(generic.ListView):
    model = Product
    template_name = 'catalog/product_list.html'
    context_object_name = 'products'
    paginate_by = 2


class CategoryListView(generic.ListView):

    template_name = 'catalog/category.html'
    context_object_name = 'product_list'
    paginate_by = 1

    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['current_category'] = get_object_or_404(
            Category, slug=self.kwargs['slug'])
        return context


def product(request, slug):
    product = Product.objects.get(slug=slug)
    context = {
        'product': product,
    }

    return render(request, 'catalog/product.html', context)


product_list = ProductListView.as_view()
category = CategoryListView.as_view()

catalog/templates/catalog/category.html
{% extends "base.html" %}

{% load pagination %}

{% block title %}
    {{ current_category }} |{{ block.super }}
{% endblock %}

{% block container %}
    <div class="page-header">
        <h1>{{ current_category }}</h1>
    </div>
    <div class="row">
    {% for product in product_list %}
        {% include "catalog/product_item.html" %}
    {% endfor %}
    </div>
    {% pagination request paginator page_obj %}
{% endblock %}

catalog/templates/catalog/product.html
{% extends "base.html" %}

{% block title %}
    {{ product }} | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
  <h1>{{ product }}</h1>
</div>
<div class="row">
  <div class="col-sm-4">
      <a href="#" class="thumbnail">
          <img src="http://placehold.it/350x250" alt="" />
      </a>
  </div>
  <div class="col-sm-8">
    <p class="text-right">
      <a href="{% url 'checkout:create_cartitem' product.slug %}" class="btn btn-success">Adicionar</a>
    </p>
      {{ product.description|linebreaks }}
  </div>
</div>
{% endblock %}

catalog/templates/catalog/product_item.html
<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <a href="#">
            <img src="http://placehold.it/350x250" alt="" />
        </a>
        <div class="caption">
            <h3> {{ product }} </h3>
            {{ product.description|linebreaks }}
            <p><a href="{{ product.get_absolute_url }}" class="btn btn-success" role="button">Detalhes</a>
            <a href="{% url 'checkout:create_cartitem' product.slug %}" class="btn btn-default" role="button">Adicionar</a></p>
        </div>
    </div>
</div>

catalog/templates/catalog/product_list.html
{% extends "base.html" %}

{% load pagination %}

{% block title %}
    Listagem de Produtos |{{ block.super }}
{% endblock %}

{% block container %}
    <div class="page-header">
        <h1>Produtos</h1>
    </div>
    <div class="row">
    {% for product in products %}
        {% include "catalog/product_item.html"%}
    {% endfor %}
    </div>
    {% pagination request paginator page_obj %}
{% endblock %}